export enum GameStateName {
  PRE_GAME = 'PRE_GAME',
  NEW_GAME = 'NEW_GAME',
  PLAY = 'PLAY',
  DONE = 'DONE',
  HAND_SETUP = 'HAND_SETUP',
  HAND_PLAY = 'HAND_PLAY',
  HAND_END = 'HAND_END',
  TRICK_START = 'TRICK_START',
  TRICK_IN_PROGRESS = 'TRICK_IN_PROGRESS',
  TRICK_END = 'TRICK_END',
}
