export enum StateEnum {

  // for testing purposes
  UNIT_TEST_STATE_A,
  UNIT_TEST_STATE_B,
  UNIT_TEST_STATE_C,
  UNIT_TEST_PARENT,
  UNIT_TEST_CHILD_A,
  UNIT_TEST_CHILD_B,
  UNIT_TEST_GRANDCHILD,
}