export enum StateEnum {
  // Game States
  GUI_STARTED,
  SELECT_DEALER,
  DEAL_CARDS,
  CURRENT_GAME,
  END_OF_HAND_ANIMATION,
  CHECK_GAME_POINTS,
  FINAL_GAME,

  // root -> used in state machine
  ROOT,
  // for testing purposes
  UNIT_TEST_STATE_A,
  UNIT_TEST_STATE_B,
  UNIT_TEST_STATE_C,
  UNIT_TEST_PARENT,
  UNIT_TEST_CHILD_A,
  UNIT_TEST_CHILD_B,
  UNIT_TEST_GRANDCHILD,
}